=== hanamanagoudaA/DevopsTest/src/main/webapp/configuration/framework/audio/sentenceLibrary.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
            xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
            jaxb:extensionBindingPrefixes="xjc" jaxb:version="1.0">

    <xsd:annotation>
        <xsd:appinfo>
            <jaxb:globalBindings generateIsSetMethod="true">
                <xjc:serializable />
            </jaxb:globalBindings>
            <jaxb:schemaBindings>
                <jaxb:package
                    name="com.nuance.framework.vxml.service.audio.content.sentence" />
            </jaxb:schemaBindings>
        </xsd:appinfo>
    </xsd:annotation>

    <xsd:element name="sentence-library" type="SentenceLibraryType" />

    <xsd:complexType name="SentenceLibraryType">
        <xsd:sequence>
            <xsd:element name="sentence" type="Sentence" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="language" type="xsd:string" />
        <xsd:attribute name="parent" type="xsd:string" />
    </xsd:complexType>


    <xsd:complexType name="Sentence">
        <xsd:sequence minOccurs="1" maxOccurs="unbounded">
            <xsd:choice>
                <xsd:element name="prompt" type="Prompt" />
                <xsd:element name="if" type="IfCondition"/>
            </xsd:choice>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required" />
        <xsd:attribute name="key" type="xsd:string" />
        <xsd:attribute name="bargein" type="xsd:boolean" default="true" />
    </xsd:complexType>
	
    <xsd:complexType name="IfCondition">
        <xsd:sequence>
            <xsd:element name="condition" type="Condition" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="prompt" type="Prompt" minOccurs="1" maxOccurs="unbounded" />
            <xsd:element name="elseif" type="ElseifCondition" minOccurs="0" maxOccurs="unbounded" />
            <xsd:element name="else" type="ElseCondition" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute name="type" default="vxml">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="vxml" />
                    <xsd:enumeration value="java" />
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="cond" type="xsd:string" use="optional" />
    </xsd:complexType>

    <xsd:complexType name="ElseifCondition">
        <xsd:sequence>
            <xsd:element name="condition" type="Condition" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="prompt" type="Prompt" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="cond" type="xsd:string" use="optional" />
    </xsd:complexType>

    <xsd:complexType name="ElseCondition">
        <xsd:sequence>
            <xsd:element name="prompt" type="Prompt" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Condition">
        <xsd:sequence>
            <xsd:element name="param" type="Param" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="classname" type="xsd:string" use="optional" />
        <xsd:attribute name="cond" type="xsd:string" use="optional" />
    </xsd:complexType>

    <xsd:complexType name="Prompt">
        <xsd:sequence>
            <xsd:element name="param" type="Param" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string">
            <xsd:annotation>
                <xsd:documentation xml:lang="en">
                    The id of the voice segment to be played.
                </xsd:documentation>
            </xsd:annotation>
        </xsd:attribute>
        <xsd:attribute name="expr" type="xsd:string" />
        <xsd:attribute name="scope" default="request">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="request" />
                    <xsd:enumeration value="session" />
                    <xsd:enumeration value="context" />
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="path" type="xsd:string" />
		
        <xsd:attribute name="type" default="application">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="application" />
                    <xsd:enumeration value="date" />
                    <xsd:enumeration value="currency" />
                    <xsd:enumeration value="number" />
                    <xsd:enumeration value="natural" />
                    <xsd:enumeration value="digits" />
                    <xsd:enumeration value="phone" />
                    <xsd:enumeration value="alphanum" />
                    <xsd:enumeration value="time" />
                    <xsd:enumeration value="tts" />
                    <xsd:enumeration value="ecmascript" />
                    <xsd:enumeration value="custom" />
                    <xsd:enumeration value="sentence" />
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="bargein" type="xsd:boolean" default="true" />
        <xsd:attribute name="cond" type="xsd:string"/>
        <xsd:attribute name="count" type="xsd:string"/>
        <xsd:attribute name="text" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="Param">
        <xsd:attribute name="name" type="xsd:string"
                               use="required" />
        <xsd:attribute name="value" type="xsd:string"
                               use="required" />
        <xsd:attribute name="scope" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="request" />
                    <xsd:enumeration value="session" />
                    <xsd:enumeration value="context" />
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="path" type="xsd:string" />
    </xsd:complexType>
</xsd:schema>

=== hanamanagoudaA/DevopsTest/src/main/webapp/configuration/application/audio/AuthMemberClaimSentences.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sentence-library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="default" language="en-US,es-US" xsi:noNamespaceSchemaLocation="../../framework/audio/sentenceLibrary.xsd">

    <sentence id="ac0140_GetMemberIDConstrainedGmr_DM_initial">
        <prompt id="ac0140_ini_01"></prompt>
    </sentence>
    <sentence id="ac0140_GetMemberIDConstrainedGmr_DM_confirmation_initial">
        <if cond="lastresult != 'NULL' &amp;&amp; lastresult != null &amp;&amp; lastresult != ''">
            <prompt id="ac0140_cnf_ini_01"/>
            <prompt type="alphanum" expr="lastresult" path="interpretation.dm_root" scope="request">
                <param name="intonation" value="f"/>
            </prompt>
            <prompt id="ac0140_cnf_ini_03"/>
        </if>
    </sentence>
    <sentence id="ac0140_GetMemberIDConstrainedGmr_DM_noinput_1">
        <prompt id="ac0140_ni1_01"/>
    </sentence>
    <sentence id="ac0140_GetMemberIDConstrainedGmr_DM_noinput_2">
        <prompt id="ac0140_ni2_01"/>
    </sentence>
    <sentence id="ac0140_GetMemberIDConstrainedGmr_DM_nomatch_1">
        <prompt id="ac0140_nm1_01"/>
    </sentence>
    <sentence id="ac0140_GetMemberIDConstrainedGmr_DM_nomatch_2">
        <prompt id="ac0140_nm2_01"/>
    </sentence>
    <sentence id="ac0150_ConfirmFirstName_DM_initial">
        <prompt id="ac0150_ini_02"/>
        <prompt type="tts" expr="firstName"/>
        <prompt id="ac0150_ini_04"/>
    </sentence>
    <sentence id="ac0150_ConfirmFirstName_DM_success">
        <prompt id="ac0150_out_01" cond="collect.value.dm_root == 'false'"/>
    </sentence>
    <sentence id="ac0150_ConfirmFirstName_DM_noinput_1">
        <prompt id="ac0150_ni1_01"/>
        <prompt type="tts" expr="firstName"/>
        <prompt id="ac0150_ni1_03"/>
    </sentence>
    <sentence id="ac0150_ConfirmFirstName_DM_noinput_2">
        <prompt id="ac0150_ni2_01"/>
        <prompt type="tts" expr="firstName"/>
        <prompt id="ac0150_ni2_03"/>
    </sentence>
    <sentence id="ac0150_ConfirmFirstName_DM_nomatch_1">
        <prompt id="ac0150_nm1_01"/>
        <prompt type="tts" expr="firstName"/>
        <prompt id="ac0150_nm1_03"/>
    </sentence>
    <sentence id="ac0150_ConfirmFirstName_DM_nomatch_2">
        <prompt id="ac0150_nm2_01"/>
        <prompt type="tts" expr="firstName"/>
        <prompt id="ac0150_nm2_03"/>
    </sentence>
    <sentence id="ac0160_GetMemberIDStaticGmr_DM_initial">
        <prompt id="ac0160_ini_02"/>
    </sentence>
    <sentence id="ac0160_GetMemberIDStaticGmr_DM_noinput_1">
        <prompt id="ac0160_ni1_01"/>
    </sentence>
    <sentence id="ac0160_GetMemberIDStaticGmr_DM_noinput_2">
        <prompt id="ac0160_ni2_01"/>
    </sentence>
    <sentence id="ac0160_GetMemberIDStaticGmr_DM_nomatch_1">
        <prompt id="ac0160_nm1_01"/>
    </sentence>
    <sentence id="ac0160_GetMemberIDStaticGmr_DM_nomatch_2">
        <prompt id="ac0160_nm2_01"/>
    </sentence>
    <sentence id="ac0160_GetMemberIDStaticGmr_DM_confirmation_initial">
        <if cond="lastresult != 'NULL' &amp;&amp; lastresult != null &amp;&amp; lastresult != ''">
            <prompt id="ac0160_cnf_ini_01" />
            <prompt type="alphanum" expr="lastresult" path="interpretation.dm_root" scope="request">
                <param name="intonation" value="f"/>
            </prompt>
            <prompt id="ac0160_cnf_ini_03"/>
        </if>
    </sentence>
    <sentence id="ac0162_GetMemberIDStaticGmrOneTry_DM_initial">
        <prompt id="ac0162_ini_01"/>
    </sentence>
    <sentence id="ac0162_GetMemberIDStaticGmrOneTry_DM_noinput_1">
        <prompt id="ac0162_ni1_01"/>
    </sentence>
    <sentence id="ac0162_GetMemberIDStaticGmrOneTry_DM_nomatch_1">
        <prompt id="ac0162_nm1_01"/>
    </sentence>
    <sentence id="ac0162_GetMemberIDStaticGmrOneTry_DM_confirmation_initial">
        <if cond="lastresult != 'NULL' &amp;&amp; lastresult != null &amp;&amp; lastresult != ''">
            <prompt id="ac0162_cnf_ini_01" />
            <prompt type="alphanum" expr="lastresult" path="interpretation.dm_root" scope="request">
                <param name="intonation" value="f"/>
            </prompt>
            <prompt id="ac0162_cnf_ini_03"/>
        </if>
    </sentence>
    <sentence id="ac0220_GetState_DM_initial">
        <prompt id="ac0220_ini_01"/>
    </sentence>
    <sentence id="ac0220_GetState_DM_noinput_1">
        <prompt id="ac0220_ni1_01"/>
    </sentence>
    <sentence id="ac0220_GetState_DM_noinput_2">
        <prompt id="ac0220_ni2_01"/>
    </sentence>
    <sentence id="ac0220_GetState_DM_nomatch_1">
        <prompt id="ac0220_nm1_01"/>
    </sentence>
    <sentence id="ac0220_GetState_DM_nomatch_2">
        <prompt id="ac0220_nm2_01"/>
    </sentence>
    <sentence id="ac0220_GetState_DM_confirmation_initial">
        <prompt id="ac0220_cnf_ini_01"/>
        <prompt type="ecmascript" expr="es;en-US/scripts/framework/ndm/confirmations.es;confirmCustomContext;1"/>
        <prompt id="ac0220_cnf_ini_03"/>
    </sentence>

    <sentence id="ac0435_GetLastNameConstrainedGmrIRIS_DM_initial">
        <prompt id="ac0435_ini_01"/>
    </sentence>
    <sentence id="ac0435_GetLastNameConstrainedGmrIRIS_DM_noinput_1">
        <prompt id="ac0435_ni1_01"/>
    </sentence>
    <sentence id="ac0435_GetLastNameConstrainedGmrIRIS_DM_nomatch_1">   
        <prompt id="ac0435_nm1_01"/>
    </sentence>
    <sentence id="ac0435_GetLastNameConstrainedGmrIRIS_DM_confirmation_initial">
        <if cond="lastresult != 'NULL' &amp;&amp; lastresult != null &amp;&amp; lastresult != ''">
            <prompt id="ac0435_cnf_ini_01"/>
            <prompt type="tts" expr="lastresult" path="interpretation.dm_root" scope="request"/>
            <prompt id="ac0435_cnf_ini_03"/>
        </if>
    </sentence>

    <sentence id="ac0440_GetLastNameConstrainedGmr_DM_initial">
        <prompt id="ac0440_ini_01"/>
    </sentence>
    <sentence id="ac0440_GetLastNameConstrainedGmr_DM_noinput_1">
        <prompt id="ac0440_ni1_01"/>
    </sentence>
    <sentence id="ac0440_GetLastNameConstrainedGmr_DM_noinput_2">   
        <prompt id="ac0440_ni2_01"/>
    </sentence>
    <sentence id="ac0440_GetLastNameConstrainedGmr_DM_nomatch_1">   
        <prompt id="ac0440_nm1_01"/>
    </sentence>
    <sentence id="ac0440_GetLastNameConstrainedGmr_DM_nomatch_2">   
        <prompt id="ac0440_nm2_01"/>
    </sentence>
    <sentence id="ac0440_GetLastNameConstrainedGmr_DM_confirmation_initial">
        <if cond="lastresult != 'NULL' &amp;&amp; lastresult != null &amp;&amp; lastresult != ''">
            <prompt id="ac0440_cnf_ini_01"/>
            <prompt type="tts" expr="lastresult" path="interpretation.dm_root" scope="request"/>
            <prompt id="ac0440_cnf_ini_03"/>
        </if>
    </sentence>
    <sentence id="ac0450_GetFirstNameConstrainedGmr_DM_initial">
        <prompt id="ac0450_ini_01"/>
    </sentence>
    <sentence id="ac0450_GetFirstNameConstrainedGmr_DM_noinput_1">
        <prompt id="ac0450_ni1_01"/>
    </sentence>
    <sentence id="ac0450_GetFirstNameConstrainedGmr_DM_noinput_2">
        <prompt id="ac0450_ni2_01"/>
    </sentence>
    <sentence id="ac0450_GetFirstNameConstrainedGmr_DM_nomatch_1">
        <prompt id="ac0450_nm1_01"/>
    </sentence>
    <sentence id="ac0450_GetFirstNameConstrainedGmr_DM_nomatch_2">
        <prompt id="ac0450_nm2_01"/>
    </sentence>
    <sentence id="ac0450_GetFirstNameConstrainedGmr_DM_confirmation_initial">
        <if cond="lastresult != 'NULL' &amp;&amp; lastresult != null &amp;&amp; lastresult != ''">
            <prompt id="ac0450_cnf_ini_01"/>
            <prompt type="tts" expr="lastresult" path="interpretation.dm_root" scope="request"/>
            <prompt id="ac0450_cnf_ini_03"/>
        </if>
    </sentence>
    <sentence id="ac0450_GetFirstNameConstrainedGmr_DM_success">
        <prompt id="ac0450_out_01"/>
    </sentence>
</sentence-library>
